version: '3.9'

services:
  app:
    build: .
    container_name: fastapi_container
    restart: on-failure
    command: uvicorn db.main:app --host 0.0.0.0
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    container_name: db_fastapi_container
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fastapi

volumes:
  postgres_data: